apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
  timeout: 2m
  interval: 30m
  values:
    controller:
      kind: DaemonSet
      hostNetwork: true
      service:
        type: ClusterIP
