apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.3"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
  interval: 10m
  values:
    controller:
      kind: DaemonSet
      hostNetwork: true
      publishService:
        enabled: false
      service:
        type: ClusterIP
