apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./../cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
