apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-exporter
  namespace: jobwatch-prod
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-redis-exporter
      version: 6.19.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    redis:
      addr: "redis://redis-service:6379"
    service:
      type: ClusterIP
      port: 9121
    serviceMonitor:
      enabled: true
      namespace: jobwatch-prod
      interval: 15s
      labels:
        release: kube-prometheus-stack
