# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: nginx-ingress
#   namespace: ingress-nginx
# spec:
#   chart:
#     spec:
#       chart: ingress-nginx
#       version: 4.13.3
#       reconcileStrategy: ChartVersion
#       sourceRef:
#         kind: HelmRepository
#         name: nginx-ingress
#         namespace: flux-system
#   interval: 30m
#   timeout: 2m
#   values:
#     controller:
#       kind: DaemonSet
#       hostNetwork: true
#       service:
#         type: ClusterIP
#       metrics:
#         enabled: true
#         service:
#           annotations:
#             prometheus.io/scrape: "true"
#             prometheus.io/port: "10254"
#         serviceMonitor:
#           enabled: true
#           additionalLabels:
#             release: kube-prometheus-stack
#         port: 10254
#         portName: metrics
