# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: selfsigned-homelab
# spec:
#   selfSigned: {}
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: homelab-ca-issuer
# spec:
#   ca:
#     secretName: homelab-ca-keypair
