apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab
  namespace: cert-manager
spec:
  secretName: wildcard-homelab-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  commonName: "*.homelab"
  dnsNames:
    - "*.homelab"
    - "homelab"
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
