---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor-ingress
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: true
    cert-manager.io/cluster-issuer: homelab-ca-issuer
spec:
  tls:
    - hosts:
        - flux.homelab
      secretName: wildcard-homelab-tls
  ingressClassName: nginx
  rules:
    - host: flux.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capacitor
                port:
                  number: 9000
