apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobwatch-backend
  namespace: jobwatch-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobwatch-backend
  template:
    metadata:
      labels:
        app: jobwatch-backend
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: backend
          image: ghcr.io/ethangilles/job-watch-backend:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jobwatch-dev
  labels:
    app: jobwatch-backend
spec:
  selector:
    app: jobwatch-backend
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
