apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: jobwatch
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux
        email: flux[bot]@github.com
      messageTemplate: 'Update JobWatch images to {{ .NewTag }}'
    push:
      branch: main
  update:
    path: ./apps/jobwatch/dev

