apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobwatch-ingress
  namespace: jobwatch-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - jobwatch.dev.homelab
      secretName: wildcard-homelab-tls
  ingressClassName: nginx
  rules:
    - host: jobwatch.dev.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
