apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobwatch-ingress
  namespace: jobwatch-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - jobwatch.dev.homelab
      secretName: wildcard-homelab-tls
  rules:
    - host: jobwatch.dev.homelab
      http:
        paths:
          # Backend API
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 8000

          # Frontend React App (catch-all)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

