apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-exporter
  namespace: jobwatch-dev
spec:
  chart:
    spec:
      chart: prometheus-redis-exporter
      version: "5.7.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 30m
  values:
    redis:
      addr: "redis://redis-service:6379"
    service:
      type: ClusterIP
      port: 9121
    serviceMonitor:
      enabled: true
      interval: "15s"
      additionalLabels:
        release: kube-prometheus-stack
      selector:
        matchLabels:
          app: redis-exporter
