apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: jobwatch-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: redisexporter/redis-exporter:v1.49.0
          args:
            - "--redis.addr=redis://redis-service:6379"
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
  namespace: jobwatch-dev
spec:
  selector:
    app: redis-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: jobwatch-dev
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: metrics
      interval: 15s
