apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-exporter
  namespace: jobwatch-dev
spec:
  chart:
    spec:
      chart: prometheus-redis-exporter
      version: 5.7.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    redis:
      addr: "redis://redis-service:6379"
    service:
      type: ClusterIP
      port: 9121
    serviceMonitor:
      enabled: true
      interval: "15s"
      selector:
        matchLabels:
          app: redis-exporter
